package network;

public enum SystemMode {
	OK,
	NOT_OK,
	LOGIN, REGISTER, GPSPOINTS, GETPLACESFROMSRVR, GETROUTESFROMSRVR, GETPATHXPLACEFROMSRVR, GETFILEFROMSERVER, GETSTATIONFORPLACE, PRINT_DISTANCE, 
}
